"""Migrate old db to new schema

Revision ID: 541497bde999
Revises:
Create Date: 2025-11-27 06:17:11.329858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '541497bde999'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('android_metadata')
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('edited_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key('fk_message_parent_id_message', 'message', ['parent_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_seen', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('online', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('online')
        batch_op.drop_column('last_seen')

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_constraint('fk_message_parent_id_message', type_='foreignkey')
        batch_op.drop_column('edited_at')
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('parent_id')

    op.create_table('android_metadata',
    sa.Column('locale', sa.TEXT(), nullable=True)
    )
    # ### end Alembic commands ###
